### PR TITLE
adds snappy and defate (zlib) compression

### PR DESCRIPTION
**Pull request by uucico**
Hello. I made some changes to enable snappy and deflate (via zlib) compression. As expected, basic testing shows snappy to be much less cpu-bound than pglz and deflate costlier, but providing higher compression rates.

At your convenience, shall we discuss if the code looks good to merge? Please note this is a very bare bones implementation, so please do criticize and recommend changes so I can improve it. I hope this proves useful somehow.

Thank you.

### CODE REVIEW

**Comment by mtuncer** [comment]
Hello @uucico 

Thanks for submitting the pull request. We are in the middle of making some other changes. In order to prevent any possible conflicts I would like to defer this until other work is completed. It would take about a week before I could take a look into this.

Meanwhile could you : 
- make sure you have signed CLA at https://cla.citusdata.com/
- address this PR to develop branch instead of master branch
- rebase changes from coming 2 PRs to develop branch. (I will update here on when to do that)

**Comment by mtuncer** [comment]
It has been 2 months and cstore_fdw 1.6 is out. It looks like we need to evaluate this for 2.0 version.

**Comment by gabitoju** [comment]
Hello.
Are you planning to do something with this PR? It's been almost a year and it would be great to have different compression algorithms to choose from.
Or maybe it's time to implement things like RLE encoding o dictionary encoding for strings?

**Comment by mtuncer** [comment]
Hello @gabitoju
Unfortunately there is no immediate plan on merging this PR at the moment.

**Comment by uucico** [comment]
I'll be rebasing from develop_v1x and retest and then include the SQL scripts to keep the coverage, then resubmit if there's still interest.

**Pull request closed without merging**
